assembly_paging.o: assembly_paging.S
boot.o: boot.S multiboot.h x86_desc.h types.h
contextSwitch.o: contextSwitch.S x86_desc.h types.h
flushPaging.o: flushPaging.S
systemcall_wrapper.o: systemcall_wrapper.S
wrapper.o: wrapper.S wrapper.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h types.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h lib.h types.h x86_desc.h wrapper.h keyboard.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h keyboard.h paging.h filesys.h systemcalls.h \
  terminal.h
keyboard.o: keyboard.c keyboard.h lib.h types.h i8259.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h x86_desc.h types.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h
systemcalls.o: systemcalls.c systemcalls.h types.h filesys.h lib.h \
  terminal.h keyboard.h rtc.h paging.h x86_desc.h
terminal.o: terminal.c terminal.h keyboard.h lib.h types.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h i8259.h idt.h rtc.h \
  filesys.h keyboard.h terminal.h
